all: submarine robbery

submarine: submarine.o
	g++ -o submarine submarine.o

submarine.o: submarine.cpp
	g++ -c -g -o submarine.o submarine.cpp

robbery: robbery.o
	g++ -o robbery robbery.o

roberry.o: robbery.cpp
	g++ -c -g -o robbery.o robbery.cpp