all:driveme driveme2 driveme3

driveme: driveme.o
	g++ -o driveme driveme.o

driveme.o: driveme.cpp
	g++ -c -g -o driveme.o driveme.cpp

driveme2: driveme2.o
	g++ -o driveme2 driveme2.o

driveme2.o: driveme2.cpp
	g++ -c -g -o driveme2.o driveme2.cpp

driveme3: driveme3.o
	g++ -o driveme3 driveme3.o

driveme3.o: driveme3.cpp
	g++ -c -g -o driveme3.o driveme3.cpp